apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.0
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    advertise-address: 192.168.2.2
    bind-address: 192.168.2.2
#controllerManager:
#  extraArgs:
#    bind-address: 192.168.2.2
#scheduler:
#  extraArgs:
#    bind-address: 192.168.2.2
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.2.2
  bindPort: 6443
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 192.168.2.2
